alias tgit='"c:/Program Files/TortoiseGit/bin/TortoiseGitProc.exe"'
alias tgl='tgit /command:log &'
alias tgc='tgit /command:commit &'
alias tgr='tgit /command:resolve &'
alias tgrb='tgit /command:rebase &'
